# Generated by Django 2.0.1 on 2018-01-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_topic_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_warning',
            field=models.BooleanField(default=False, verbose_name='Aviso'),
        ),
    ]
