# Generated by Django 2.0.1 on 2018-01-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank='true', default='avatar/user.png', upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
