# Generated by Django 2.0.1 on 2018-01-20 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipline', '0002_remove_discipline_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Professor(a)'),
            preserve_default=False,
        ),
    ]
