# Generated by Django 2.0.1 on 2018-01-21 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipline', '0003_discipline_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Aguardando Confirmação'), (1, 'Adicionado na Disciplina'), (2, 'Solicitação Recusada')], default=0, verbose_name='Situação')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discipline.Discipline', verbose_name='Disciplina')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
        ),
    ]
