# Generated by Django 2.0.1 on 2018-01-21 04:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipline', '0004_registestudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteStudent',
            new_name='RegisterStudent',
        ),
    ]
