# Generated by Django 2.0.1 on 2018-01-22 02:24

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipline', '0005_auto_20180121_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerstudent',
            options={'ordering': ['-join'], 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AddField(
            model_name='registerstudent',
            name='join',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registrado'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='registerstudent',
            unique_together={('student', 'discipline')},
        ),
    ]
