# Generated by Django 2.0.1 on 2018-01-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0006_auto_20180121_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aguardando Confirmação'), (1, 'Adicionado na Disciplina'), (2, 'Solicitação Recusada'), (3, 'Administrador')], default=0, verbose_name='Situação'),
        ),
    ]
