# Generated by Django 2.0.1 on 2018-01-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(default=1, upload_to='materials', verbose_name='Material'),
            preserve_default=False,
        ),
    ]
