# Generated by Django 2.0.1 on 2018-01-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_material_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descição'),
        ),
    ]
