# Generated by Django 2.0.1 on 2018-01-24 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0003_auto_20180124_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='shared_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado por'),
            preserve_default=False,
        ),
    ]
